### Create a Short Url
POST {{baseUrl}}/shorten
Content-Type: application/json

{
  "longUrl":  "longUrl",
  "shortCode": "(Optional) shortCode, (will be created automatically if empty)"
}

### Redirect to short Url

GET {{baseUrl}}/{shortCode}

### Get details

GET {{baseUrl}}/details/{shortCode}

### Toggle Url State

PATCH {{baseUrl}}/state/{id}
Content-Type: application/json

{
  "isActive": "boolean"
}

### Update ShortUrl

PUT {{baseUrl}}/update/{id}
Content-Type: application/json

{
  "shortCode": "(Optional) new shortCode",
  "longUrl": "(Optional) new longUrl"
}
