### Create a Short Url
POST http://localhost:3000/shorten
Content-Type: application/json

{
  "longUrl":  "longUrl",
  "shortCode": "(Optional) shortCode, (will be created automatically if empty)"
}

### Redirect to short Url

GET http://localhost:3000/{shortCode}

### Get details

GET http://localhost:3000/details/{shortCode}

### Toggle Url State

PATCH http://localhost:3000/state/{id}
Content-Type: application/json

{
  "isActive": "boolean"
}

### Update ShortUrl

PUT http://localhost:3000/update/{id}
Content-Type: application/json

{
  "shortCode": "(Optional) new shortCode",
  "longUrl": "(Optional) new longUrl"
}
